/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-surface': '#2e3132',
        'inverse-primary': '#81d6c0',
        'on-tertiary': '#ffffff',
        'tertiary': '#005513',
        'secondary-fixed': '#ffdbc8',
        'secondary-fixed-dim': '#ffb68b',
        'surface-container-high': '#e7e8e9',
        'surface-container-highest': '#e1e3e4',
        'on-surface': '#191c1d',
        'surface-container-lowest': '#ffffff',
        'tertiary-container': '#00701c',
        'on-primary-fixed-variant': '#005143',
        'surface-bright': '#f8f9fa',
        'secondary-container': '#fb7800',
        'tertiary-fixed': '#70ff76',
        'on-error-container': '#93000a',
        'on-primary': '#ffffff',
        'surface-dim': '#d9dadb',
        'primary-container': '#006d5b',
        'surface-variant': '#e1e3e4',
        'primary': '#005344',
        'primary-fixed-dim': '#81d6c0',
        'on-error': '#ffffff',
        'secondary': '#994700',
        'error': '#ba1a1a',
        'primary-fixed': '#9df3dc',
        'surface-tint': '#006b59',
        'outline': '#6e7975',
        'on-secondary-fixed-variant': '#753400',
        'on-secondary-container': '#592600',
        'background': '#f8f9fa',
        'outline-variant': '#bec9c4',
        'on-background': '#191c1d',
        'on-primary-container': '#96ebd5',
        'on-secondary-fixed': '#321200',
        'error-container': '#ffdad6',
        'tertiary-fixed-dim': '#42e355',
        'on-tertiary-fixed': '#002204',
        'on-secondary': '#ffffff',
        'surface-container-low': '#f3f4f5',
        'on-tertiary-container': '#5bf968',
        'on-primary-fixed': '#00201a',
        'inverse-on-surface': '#f0f1f2',
        'surface': '#f8f9fa',
        'on-tertiary-fixed-variant': '#005313',
        'surface-container': '#edeeef',
        'on-surface-variant': '#3e4945',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Plus Jakarta Sans'],
        body: ['Inter'],
        label: ['Inter'],
      },
    },
  },
  plugins: [],
};
